[package]
name = "adamantium-cli"
version.workspace = true
edition.workspace = true
license-file = "../../LICENSE.md"
build = "build.rs"

[[bin]]
name = "adamantium"
path = "src/main.rs"

[dependencies]
adamantium-compiler = { path = "../adamantium-compiler" }
adamantium-diagnostics = { path = "../adamantium-diagnostics" }
adamantium-fmt = { path = "../adamantium-fmt" }
adamantium-ir = { path = "../adamantium-ir" }
adamantium-linker = { path = "../adamantium-linker" }
adamantium-packages = { path = "../adamantium-packages" }
adamantium-project = { path = "../adamantium-project" }
adamantium-testing = { path = "../adamantium-testing" }
adamantium-types = { path = "../adamantium-types" }
adamantium-wasm = { path = "../adamantium-wasm" }
toml.workspace = true
rustc_apfloat.workspace = true

[dev-dependencies]
wat.workspace = true
