[package]
name = "adamantium-semantics"
version.workspace = true
edition.workspace = true
license-file = "../../LICENSE.md"

[dependencies]
adamantium-lexer = { path = "../adamantium-lexer" }
adamantium-hir = { path = "../adamantium-hir" }
adamantium-parser = { path = "../adamantium-parser" }
adamantium-types = { path = "../adamantium-types" }
adamantium-diagnostics = { path = "../adamantium-diagnostics" }
