[package]
name = "adamantium-runtime"
version.workspace = true
edition.workspace = true
license-file = "../../LICENSE.md"

[lib]
crate-type = ["staticlib", "rlib"]

[dependencies]
adamantium-types = { path = "../adamantium-types" }
adamantium-wasm = { path = "../adamantium-wasm" }
rustc_apfloat = "=0.2.3"
wasmi = "2.0.0"
wasmi_wasi = "2.0.0"

[dev-dependencies]
wat.workspace = true
