[package]
name = "adamantium-lowering"
version.workspace = true
edition.workspace = true
license-file = "../../LICENSE.md"

[dependencies]
adamantium-hir = { path = "../adamantium-hir" }
adamantium-mir = { path = "../adamantium-mir" }
adamantium-ir = { path = "../adamantium-ir" }
adamantium-types = { path = "../adamantium-types" }
