name: Proof HTML

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  proof-html:
    name: Check documentation links
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out tested revision
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Check HTML and Markdown links
        uses: anishathalye/proof-html@v1.1.0
        with:
          directory: ./
